services:
  frontend:
    container_name: sanecta-frontend

    build:
      context: ./sanecta-frontend
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"

    volumes:
      - ./sanecta-frontend:/app
      - node_modules:/app/node_modules

    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

volumes:
  node_modules: